name: Build Custom Kernel for Crownlte

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
        kernel-url: ./
        config: crownlte_defconfig
        arch: arm64
        aosp-clang: true
        anykernel3: true
        release: true
