name: Build Final Kernel for Crownlte (N960F)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: cyberknight777/kernel_build_action@main
      with:
        kernel-url: ./
        kernel-dir: .
        config: crownlte_defconfig
        arch: arm64
        toolchain: gcc
        anykernel3: true
        release: true
